[build]
  base    = "./"
  command = "yarn build"
  publish = "./build"

[context.production.environment]
  REACT_APP_STAGE = "production"

[context.deploy-preview.environment]
  REACT_APP_STAGE = "staging"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
