apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  # postgres
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_USER: "${POSTGRES_USER}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hapi-config
data:
  # hapi
  HAPI_POSTGRES_HOST: "${HAPI_POSTGRES_HOST}"
  HAPI_POSTGRES_DB: "${HAPI_POSTGRES_DB}"
  HAPI_POSTGRES_PASSWORD: "${HAPI_POSTGRES_PASSWORD}"
  HAPI_HASURA_URL: "${HAPI_HASURA_URL}"
  HAPI_HASURA_ADMIN_SECRET: "${HAPI_HASURA_ADMIN_SECRET}"
  HAPI_POSTGRES_PORT: "${HAPI_POSTGRES_PORT}"
  HAPI_POSTGRES_SCHEMA: "${HAPI_POSTGRES_SCHEMA}"
  HAPI_POSTGRES_USER: "${HAPI_POSTGRES_USER}"
  HAPI_EOS_API_ENDPOINT: "${HAPI_EOS_API_ENDPOINT}"
  HAPI_EOS_CHAIN_ID: "${HAPI_EOS_CHAIN_ID}"
  HAPI_SERVER_ADDRESS: "${HAPI_SERVER_ADDRESS}"
  HAPI_SERVER_PORT: "${HAPI_SERVER_PORT}"
  HAPI_VALID_USERS: "${HAPI_VALID_USERS}"
  HAPI_PROXY_CONTRACT: "${HAPI_PROXY_CONTRACT}"
  HAPI_RATING_CONTRACT: "${HAPI_RATING_CONTRACT}"
  HAPI_HYPERION_API: "${HAPI_HYPERION_API}"
  HAPI_HYPERION_START_AT: "${HAPI_HYPERION_START_AT}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-config
data:
  # hasura
  HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
  HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
  HASURA_GRAPHQL_ACTION_BASE_URL: "${HASURA_GRAPHQL_ACTION_BASE_URL}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgweb-config
data:
  # pgweb
  DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
