name: Build images from latest staging branch

on:
  push:
    branches:
      - staging

jobs:
  create-staging-image:
    name:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Log in to docker registry
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login \
            --username ${{ secrets.DOCKER_HUB_USER }} \
            --password-stdin

      - name: Install node module dependencies
        run: |
          cd services/hapi
          yarn
          cd ../frontend
          yarn
          cd ../..

      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          # general
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          BRANCH: staging
          NAMESPACE: jungle-eosrate

      - name: Build kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          # general
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          BRANCH: staging
          NAMESPACE: jungle-eosrate
          INGRESS_HOST: jungle.eosrate.io
          INGRESS_GRAPHQL_HOST: graphql-jungle.eosrate.io
          # webapp
          REACT_APP_GRAPHQL_HTTP_URL: https://graphql-jungle.eosrate.io/v1/graphql
          REACT_APP_GRAPHQL_WS_URL: ws://localhost:8080/v1/graphql
          REACT_APP_EOS_API_URL: https://jungle.eosio.cr
          REACT_APP_EOS_API_HOST: jungle.eosio.cr
          REACT_APP_EOS_API_PORT: 443
          REACT_APP_EOS_API_PROTOCOL: https
          REACT_APP_EOS_CHAIN_ID: 2a02a0053e5a8cf73a56ba0fda11e4d92e0238a4a2aa74fccf46d5a910746840
          REACT_APP_BLOCK_EXPLORER: https://jungle3.bloks.io
          # postgres
          DATABASE_DIRECTORY: database
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          # hapi
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: "5432"
          DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
          EOS_API_ENDPOINT: https://jungle3.cryptolions.io
          VIRTUAL_HOST: 0.0.0.0
          VIRTUAL_PORT: 9090
          # hasura
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${{ secrets.HASURA_GRAPHQL_UNAUTHORIZED_ROLE }}
          HASURA_GRAPHQL_ACTION_BASE_URL: ${{secrets.HASURA_GRAPHQL_ACTION_BASE_URL}}
          # pgweb
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Setup and deploy kubernetes environment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: jungle-eosrate
          K8S_BUILD_DIR: build_k8s
        with:
          args: version && make deploy-kubernetes
